### PR TITLE
Update test branch

### PR DESCRIPTION
**Pull request by can-aslan**

### CODE REVIEW

**Review by selimcanglr — APPROVED** [review]

**Review by tolgaozgun — DISMISSED** [review]
LGTM

**Comment by tolgaozgun** [comment]
Let's review after the merge of PR #6

**Review by tolgaozgun — DISMISSED** [review]
LGTM

**Review by tolgaozgun — APPROVED** [review]
LGTM

**Review by tolgaozgun — APPROVED** [review]
LGTM

**Pull request merged**
